exp:
  stage: 1
  name: base

dataset:
  name: comphyVid
  data_root: data

model:
  name: InphyGPT
  t_pe: sin
  d_model: 64
  num_layers: 4
  num_heads: 8
  ffn_dim: 256
  history_len: 3
  n_preds: 3
  T: 5
  K: 6
  a_dim: 12
  resolution: 
    - 64
    - 96
  use_feature_extractor: True
  beta: 100.

training:
  parallel: True
  batch_size: 64
  val_batch_size: 8
  num_workers: 8
  epochs: 200
  save_interval: 1
  val_interval: 1
  save_path: './'
  pretrained_path: ''

optimizer:
  lr: 0.0001
  regularization: 0

